rule:
  meta:
    name: set application hook
    rule-category: machine-access-control/application-hook-manipulation/set-application-hook
    author: michael.hunhoff@fireeye.com
    scope: function
    examples:
      - Practical Malware Analysis Lab 12-03.exe_:0x401000
  features:
    - and:
      - or:
        - api: user32.SetWindowsHookEx
        - api: user32.UnhookWindowsHookEx